wandb_version: 1

entropy_coeff:
  desc: null
  value: 2.419209208556338e-06
lr:
  desc: null
  value: 6.469109688038408e-05
sgd_minibatch_size:
  desc: null
  value: 64
lambda:
  desc: null
  value: 0.1
framework:
  desc: null
  value: torch
model:
  desc: null
  value:
    fcnet_hiddens:
    - 256
    - 256
num_envs_per_worker:
  desc: null
  value: 1000
rollout_fragment_length:
  desc: null
  value: auto
log_level:
  desc: null
  value: DEBUG
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
env:
  desc: null
  value: StockTrading_train
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687230041.194432
    t:
      1:
      - 30
      - 55
      2:
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 8
trial_log_path:
  desc: null
  value: /home/BL-Project/FINRL_TEST_MLP/FINRL_TEST_MLP/PPO_StockTrading_train_ea6e7288_1_entropy_coeff=0.0000,env=StockTrading_train,framework=torch,lambda=0.1000,log_level=DEBUG,lr=0.0_2023-06-20_03-00-36
