wandb_version: 1

params:
  desc: null
  value:
    entropy_coeff: 3.1287824843683018e-06
    lr: 5.447515828096367e-05
    sgd_minibatch_size: 128
    lambda: 1.0
    framework: torch
    model:
      fcnet_hiddens:
      - 256
      - 256
    num_envs_per_worker: 100
    rollout_fragment_length: auto
scaling_config:
  desc: null
  value:
    trainer_resources: null
    num_workers: 1
    use_gpu: true
    resources_per_worker:
      CPU: 0.1
      GPU: 0.1
    placement_strategy: PACK
    _max_cpu_fraction_per_node: null
framework:
  desc: null
  value: torch
log_level:
  desc: null
  value: DEBUG
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
env:
  desc: null
  value: StockTrading_train
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697963006.154588
    t:
      1:
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 8
      13: linux-x86_64
