wandb_version: 1

entropy_coeff:
  desc: null
  value: 2.927897515933752e-08
lr:
  desc: null
  value: 7.139297742110942e-05
sgd_minibatch_size:
  desc: null
  value: 256
lambda:
  desc: null
  value: 0.3
framework:
  desc: null
  value: torch
model:
  desc: null
  value:
    fcnet_hiddens:
    - 256
    - 256
num_envs_per_worker:
  desc: null
  value: 1000
rollout_fragment_length:
  desc: null
  value: auto
log_level:
  desc: null
  value: DEBUG
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
env:
  desc: null
  value: StockTrading_train
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687230008.681036
    t:
      1:
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 8
