wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697775758.178929
    t:
      1:
      - 1
      - 30
      - 35
      - 55
      2:
      - 1
      - 5
      - 30
      - 35
      - 53
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
