wandb_version: 1

entropy_coeff:
  desc: null
  value: 9.728308297678455e-07
lr:
  desc: null
  value: 5.874771999467174e-05
sgd_minibatch_size:
  desc: null
  value: 128
lambda:
  desc: null
  value: 0.9
framework:
  desc: null
  value: torch
model:
  desc: null
  value:
    fcnet_hiddens:
    - 256
    - 256
num_envs_per_worker:
  desc: null
  value: 10000
log_level:
  desc: null
  value: DEBUG
num_gpus:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 1
env:
  desc: null
  value: StockTrading_train
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687229507.254325
    t:
      1:
      - 30
      - 55
      2:
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 8
trial_log_path:
  desc: null
  value: /home/BL-Project/FINRL_TEST_MLP/FINRL_TEST_MLP/PPO_StockTrading_train_7fce8ecd_2_entropy_coeff=0.0000,env=StockTrading_train,framework=torch,lambda=0.9000,log_level=DEBUG,lr=0.0_2023-06-20_02-51-42
